title: "Zeher Hassan"
tagline: "Geo-Politics & Deep-Tech"
description: "Geo-Politics, Semiconductors, Deep-Tech, and In-Depth Analysis."
url: "https://zeherhassan.com"
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: /articles/:year/:month/:day/:title/
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
